[server]
hostname = "localhost"

[user_store]
type = "read_only_ldap"

[keystore.primary]
file_name = "repository/resources/security/wso2carbon.jks"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name = "repository/resources/security/client-truststore.jks"
password = "wso2carbon"
alias = "symmetric.key.value"
algorithm = "AES"

[mediation]
flow.statistics.enable=true
flow.statistics.capture_all=true

[analytics]
enabled = true

[icp_config]
enabled = true
icp_url = "https://proxy:9456"
environment = "dev"
project = "sample-project"
integration = "mi-sample-integration"
secret = "tmpmi.mi-only-dev-env-secret-for-local-use-only-do-not-use-in-production-placeholder"
